title: "Notes de boulangerie"
lang: fr_FR
show_downloads: false

twitter:
  username: adericbourg

# Front matter defaults
defaults:
- scope:
    # All pages
    path: ""
  values:
    image: "images/thumbnail.png"

plugins:
- jekyll-sitemap
